# Site settings
title: Alex Kluew - getaclue.me
email: info@getaclue.me
description: > # this means to ignore newlines until "baseurl:"
  A dream is just a dream. A goal is a dream with a plan and a deadline.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://getaclue.github.io/" # the base hostname & protocol for your site
twitter_username: alexkluew
github_username:  getaclue

# Build settings
markdown: kramdown

# Windows Problem
highlighter: false
